---
apiVersion: v1
kind: Pod
metadata:
  name: ndn-service-pod1
  labels:
    name: ndn-service-pod1
spec:
  containers:
    - name: service
      image: hydrokhoos/relay-service:test
      imagePullPolicy: Always
      tty: true
      volumeMounts:
        - mountPath: /share
          name: share-volume
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TCP_MESSAGE_PORT
          value: "1234"
        - name: SHARE_PATH
          value: /share/
    - name: sidecar
      image: hydrokhoos/ndn-sidecar:test
      imagePullPolicy: Always
      tty: true
      ports:
        - containerPort: 6363
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /share
          name: share-volume
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: TCP_MESSAGE_PORT
          value: "1234"
        - name: SHARE_PATH
          value: /share/
        - name: NDN_CLIENT_TRANSPORT
          value: tcp4://ndn-node1
        - name: ROUTER_PREFIX
          value: /ndn/jp/%C1.Router/node1
        - name: MY_SERVICE_NAME
          value: /relay
  volumes:
    - name: share-volume
      emptyDir: {}
